package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new com.example.bitmap.BitmapPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin bitmap, com.example.bitmap.BitmapPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.github.ponnamkarthik.toast.fluttertoast.FlutterToastPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin fluttertoast, io.github.ponnamkarthik.toast.fluttertoast.FlutterToastPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.tectoy.tectoy_sunmiprinter.TectoySunmiprinterPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin tectoy_sunmiprinter, com.tectoy.tectoy_sunmiprinter.TectoySunmiprinterPlugin", e);
    }
  }
}
